### ISSUE TITLE
Push通知用モジュールを追加

### ISSUE THREAD

**Issue by SatoshiN303** [SatoshiN303/Swift-Project-Template#17]
@ist-ikeno 

色々な案件を経験されてきた思いますので、まずは自分が汎用性が高いと思うものを実装してみて下さい。個人的によくある実装かと思うのは以下かと思います。適宜ご参考下さい。

* AppDelegate には処理を書かず独自の構造体で デバイストークン登録、push受信の処理等を定義する
* アプリ起動中、バックグラウウンド、未起動でハンドリングが分けられている
* payaload は構造体で定義してUnboxなりCodableでマッピング

**Comment by SatoshiN303** [comment]
@ist-ikeno 

すんません。セルフマージできるチケットで諸々develop更新してますので
大変お手数ですが最新版のマージをお願い致します

**Comment by ist-ikeno** [comment]
@satoshin-IST 承知いたしました。
